---
# tasks file for zip (CentOS specific)

- name: Install zip packages
  yum:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - "{{ zip_packages }}"
  tags:
    - zip
