---
# tasks file for zip

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: zip

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: zip

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: zip
