---
# tasks file for zip

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution|lower }}.yml"
  tags:
    - zip

- name: Include distribution specific tasks
  include: "{{ ansible_distribution|lower }}.yml"
  tags:
    - zip
